version: '2'
services:
  yiin: 
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "3000"
    volumes:
      - ~/docker/fiin/log:/var/log/fiin
    links:
      - mongo
  mongo:
    image: mongo:3.4
    ports:
      - "127.0.0.1:27017:27017"  # for host connect
    volumes:
      - ~/docker/mongodb/log:/var/log/mongodb
      - ~/docker/data/db:/data/db
  nginx:
    image: nginx:1.11-alpine 
    links:
      - yiin 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/yiin.life.conf:/etc/nginx/conf.d/yiin.life.conf
      - ~/docker/nginx/log:/var/log/nginx/

